In [1]:
import numpy as np

In [10]:
k = 1
l = 1/(k+3)
MAS = np.array([
    [180,140,k,245-4*k,232],
    [420,120+10*k,140,220,100],
    [28+8*k,315,35,49,(10*k+23)-50],
    [290-10*k,k,9,100*k-90,201]
],dtype=object)
p1 = 0.1; p2 = 0.2; p3 = l; p4 = l+0.1; p5 = 1-p1-p2-p3-p4
p = np.array([p1,p2,p3,p4,p5])

# Критерій песимізму

In [3]:
print("Масив \n",MAS)
min_j = np.amin(MAS,axis=0)
print("Найгірші результати при використанні відповідних  стратегій \n",min_j)
max_i_min_j = np.amax(min_j)
print("Найбільший прибуток в найгірших умовах",max_i_min_j)

Масив 
 [[180 140 1 241 232]
 [420 130 140 220 100]
 [36 315 35 49 -17]
 [280 1 9 10 201]]
Найгірші результати при використанні відповідних  стратегій 
 [36 1 1 10 -17]
Найбільший прибуток в найгірших умовах 36


# Критерій оптимізму

In [4]:
print("Масив \n",MAS)
max_i = np.amax(MAS,axis=0)
print("Найкращий результат кожної графи \n",max_i)
r = np.zeros(MAS.shape)
for j in range (len(MAS)):
    for i in range (len(MAS[0])):
        r[j][i] = max_i[i]-MAS[j][i]
print("Відхилення відкращого результату кожної окремої графи\n",r)
max_j = np.amax(r,axis=1)
print("Матриця жалю\n",max_j)
res = np.min(max_j,axis=0)
print("Обираємо рішення, за якого максимальний жаль буде меншим, ніж за інших рішень\n",res)
j,i = np.where(r == res); i = i[0];j=j[0]
f_res = MAS[j][i]
print(f_res,f"По стовбцям {i} і строкам {j}" )
    

Масив 
 [[180 140 1 241 232]
 [420 130 140 220 100]
 [36 315 35 49 -17]
 [280 1 9 10 201]]
Найкращий результат кожної графи 
 [420 315 140 241 232]
Відхилення відкращого результату кожної окремої графи
 [[240. 175. 139.   0.   0.]
 [  0. 185.   0.  21. 132.]
 [384.   0. 105. 192. 249.]
 [140. 314. 131. 231.  31.]]
Матриця жалю
 [240. 185. 384. 314.]
Обираємо рішення, за якого максимальний жаль буде меншим, ніж за інших рішень
 185.0
130 По стовбцям 1 і строкам 1


# Критерій песимізму-оптимізму (критерій Гурвіца).

In [5]:
max_i = np.amax(MAS, axis = 1)
min_j = np.amin(MAS, axis = 1)
mid = l*min_j+(1-l)*max_i
max_mid = np.amax(mid)
print("Масив \n",MAS,"\n Отриманий результат \n",max_mid,"\n")

module = np.absolute(MAS-max_mid)
sup_min=np.amin(np.amin(module))
j,i = np.where(sup_min == module); i = i[0];j=j[0]

print("Найближчий результат",MAS[j][i])

Масив 
 [[180 140 1 241 232]
 [420 130 140 220 100]
 [36 315 35 49 -17]
 [280 1 9 10 201]] 
 Отриманий результат 
 340.0 

Найближчий результат 315


# Критерій Байєса-Лапласа.

In [17]:
M_p = MAS*p

In [18]:
np.array([[2,2],[3,3]])*np.array([1,2])

array([[2, 4],
       [3, 6]])

In [35]:
print(M_p)
B = np.sum(M_p, axis = 1)
print("B = ", B, "\n max = ",np.amax(B),f"j={np.argmax(B)}")

[[18.0 28.0 0.25 84.35 23.199999999999996]
 [42.0 26.0 35.0 77.0 9.999999999999998]
 [3.6 63.0 8.75 17.15 -1.6999999999999997]
 [28.0 0.2 2.25 3.5 20.099999999999994]]
B =  [153.79999999999998 190.0 90.8 54.05] 
 max =  190.0 j=1


In [37]:
print(MAS)
D = np.sum(MAS, axis = 1)/len(MAS)
print("D = ", D, "\n max = ",np.amax(D),f"j={np.argmax()}")

[[180 140 1 241 232]
 [420 130 140 220 100]
 [36 315 35 49 -17]
 [280 1 9 10 201]]
D =  [198.5 252.5 104.5 125.25] 
 max =  252.5 j=1


# Критерій Ходжа-Лемана

In [42]:
print(MAS)
H = np.amax((1-l)*np.min(MAS,axis=1)+l*B)

print("Масив \n",MAS,"\n Отриманий результат \n",H,"\n")

module = np.absolute(MAS-H)
sup_min=np.amin(np.amin(module))
j,i = np.where(sup_min == module); i = i[0];j=j[0]

print("Найближчий результат",MAS[j][i])

[[180 140 1 241 232]
 [420 130 140 220 100]
 [36 315 35 49 -17]
 [280 1 9 10 201]]
Масив 
 [[180 140 1 241 232]
 [420 130 140 220 100]
 [36 315 35 49 -17]
 [280 1 9 10 201]] 
 Отриманий результат 
 122.5 

Найближчий результат 130
